apiVersion: v1
kind: Service
metadata:
  name: gamersunite
  labels:
    app: gamersunite
spec:
  type: NodePort
  selector:
    app: gamersunite
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
